-- MailDesk Pro - esquema inicial. Compatible con PostgreSQL y H2 (MODE=PostgreSQL).

CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(320) NOT NULL,
    display_name        VARCHAR(120) NOT NULL,
    password_hash       VARCHAR(512) NOT NULL,
    role                VARCHAR(20)  NOT NULL,
    status              VARCHAR(30)  NOT NULL,
    email_verified_at   TIMESTAMP WITH TIME ZONE,
    session_epoch       INTEGER      NOT NULL DEFAULT 0,
    failed_login_count  INTEGER      NOT NULL DEFAULT 0,
    locked_until        TIMESTAMP WITH TIME ZONE,
    signature_html      TEXT,
    last_login_at       TIMESTAMP WITH TIME ZONE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE invitations (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR(320) NOT NULL,
    role         VARCHAR(20)  NOT NULL,
    token_hash   VARCHAR(128) NOT NULL,
    invited_by   BIGINT       NOT NULL REFERENCES users(id),
    expires_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at      TIMESTAMP WITH TIME ZONE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_invitations_token UNIQUE (token_hash)
);
CREATE INDEX ix_invitations_email ON invitations(email);

CREATE TABLE auth_challenges (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT       NOT NULL REFERENCES users(id),
    purpose              VARCHAR(30)  NOT NULL,
    code_hmac            VARCHAR(128) NOT NULL,
    session_binding_hash VARCHAR(128) NOT NULL,
    payload              VARCHAR(320),
    attempts             INTEGER      NOT NULL DEFAULT 0,
    max_attempts         INTEGER      NOT NULL,
    expires_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at          TIMESTAMP WITH TIME ZONE,
    invalidated_at       TIMESTAMP WITH TIME ZONE,
    request_ip           VARCHAR(64),
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_auth_challenges_user ON auth_challenges(user_id, purpose, created_at);

CREATE TABLE password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users(id),
    token_hash  VARCHAR(128) NOT NULL,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at     TIMESTAMP WITH TIME ZONE,
    request_ip  VARCHAR(64),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_reset_token UNIQUE (token_hash)
);

CREATE TABLE rate_limit_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket_key  VARCHAR(200) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_rate_limit_bucket ON rate_limit_events(bucket_key, occurred_at);

CREATE TABLE app_settings (
    setting_key   VARCHAR(100) PRIMARY KEY,
    setting_value TEXT,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id     BIGINT,
    actor_email  VARCHAR(320),
    action       VARCHAR(60)  NOT NULL,
    target_type  VARCHAR(40),
    target_id    VARCHAR(80),
    details      VARCHAR(1000),
    ip_address   VARCHAR(64),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_audit_created ON audit_log(created_at);
CREATE INDEX ix_audit_actor ON audit_log(actor_id);

CREATE TABLE tags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT       NOT NULL REFERENCES users(id),
    name       VARCHAR(60)  NOT NULL,
    color      VARCHAR(7)   NOT NULL DEFAULT '#6366f1',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_tags_owner_name UNIQUE (owner_id, name)
);

CREATE TABLE contacts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT       NOT NULL REFERENCES users(id),
    full_name  VARCHAR(160) NOT NULL,
    email      VARCHAR(320) NOT NULL,
    company    VARCHAR(160),
    phone      VARCHAR(40),
    notes      VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_contacts_owner ON contacts(owner_id, full_name);
CREATE INDEX ix_contacts_owner_email ON contacts(owner_id, email);

CREATE TABLE contact_tags (
    contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    tag_id     BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (contact_id, tag_id)
);

CREATE TABLE mail_templates (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id    BIGINT       NOT NULL REFERENCES users(id),
    name        VARCHAR(120) NOT NULL,
    subject     VARCHAR(500) NOT NULL,
    body_html   TEXT         NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_templates_owner_name UNIQUE (owner_id, name)
);

CREATE TABLE messages (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id          BIGINT       NOT NULL REFERENCES users(id),
    status            VARCHAR(20)  NOT NULL,
    to_recipients     VARCHAR(4000),
    cc_recipients     VARCHAR(4000),
    bcc_recipients    VARCHAR(4000),
    subject           VARCHAR(500),
    body_html         TEXT,
    content_type      VARCHAR(10)  NOT NULL DEFAULT 'HTML',
    include_signature BOOLEAN      NOT NULL DEFAULT TRUE,
    submission_token  VARCHAR(64),
    message_id_header VARCHAR(255),
    attempts          INTEGER      NOT NULL DEFAULT 0,
    last_error        VARCHAR(1000),
    smtp_response     VARCHAR(500),
    next_attempt_at   TIMESTAMP WITH TIME ZONE,
    locked_at         TIMESTAMP WITH TIME ZONE,
    queued_at         TIMESTAMP WITH TIME ZONE,
    sent_at           TIMESTAMP WITH TIME ZONE,
    failed_at         TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_messages_submission UNIQUE (submission_token)
);
CREATE INDEX ix_messages_owner_status ON messages(owner_id, status, updated_at);
CREATE INDEX ix_messages_queue ON messages(status, next_attempt_at);

CREATE TABLE attachments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id    BIGINT       NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    owner_id      BIGINT       NOT NULL REFERENCES users(id),
    original_name VARCHAR(255) NOT NULL,
    stored_name   VARCHAR(80)  NOT NULL,
    content_type  VARCHAR(120) NOT NULL,
    size_bytes    BIGINT       NOT NULL,
    sha256        VARCHAR(64)  NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_attachments_stored UNIQUE (stored_name)
);
CREATE INDEX ix_attachments_message ON attachments(message_id);
